// Client/Admin/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  
}

<header>
    <div class="container">
        <img src="logo.png" alt="muganim logo">
        <nav>
            <ul>
                <li>
                    <a routerLink="/">Home</a>
                </li>
                @if(false){
                <li>
                    <a routerLink="/login">Log In</a>
                </li>}
                @else {
                <li>
                    <a routerLink="/manage-users">Users</a>
                </li>
                <li>
                    <a routerLink="/manage-files">Files</a>
                </li>
                }
            </ul>
        </nav>
        <div id="humburger">
            <div></div>
        </div>
    </div>
</header>

// Client/Users/src/components/header/header.tsx
import { useContext, useEffect } from "react";
import MyWorkspace from "./my-workspace";
import { userContext } from "../../contexts/user-context";
import AuthNav from "./auth-nav";
import { useNavigate } from "react-router-dom";
import * as logo from "../../assets/logo.png"

const Header = () => {
    const { userState } = useContext(userContext);
    const navigate = useNavigate();

    useEffect(() => {
        if (userState.state === "not logged in") {
            navigate("/login");
        }
    }, [userState.state, navigate]);

    return <>
        <header>
            <div className="container">
                <img src={logo.default} alt="muganim logo" />
                <nav>
                    <ul>
                        {userState.state === "not logged in" ? <AuthNav /> : <MyWorkspace />}
                    </ul>
                </nav>
                <div id="humburger">
                    <div></div>
                </div>
            </div>
        </header>
    </>
}
export default Header;
